### ISSUE TITLE
Working on RX 570X

### ISSUE THREAD

**Issue by user987098** [AirGibson/RocmStableDiffusion#3]
following your guide i was able to get both running on my RX 570 XFX, i am experiencing some slight screen flickering after starting the container and python 3.10 crashed

**Comment by user987098** [comment]
I forgot to mention the OS and CPU

Ubuntu LTS 22.40.4 
Ryzen 5 5600X
RX 570X XFX

Only Kohya works out the gate, you need to build and add the gfx803.dat file to the tensile library to get stable diffsusion running

**Comment by AirGibson** [comment]
Can you elaborate on the "gfx803.dat" file?  Happy to include it if it doesn't disrupt things.

**Comment by user987098** [comment]
this is just for a really old gpu support i wouldn't add it in, if anybody needs support on an old gpu either downgrade rcom and related packages to your last supported version or go to rocblas and cmake your .dat file, plenty of youtube videos on it

**Comment by AirGibson** [comment]
Notes regarding RX 570X XFX have been added
