### ISSUE TITLE
extensions and --listen

### ISSUE THREAD

**Issue by DJHanceNL** [AirGibson/RocmStableDiffusion#4]
most of it is working, i'm really learning a lot. But the issue i have, i cant install any extensions

i found that --listen disables extensions, and adding this to command AGR --global-extensions-access should fix it.

But how do the variables work? I changed it in dockerfile in the orginal RocmStableDiffusion in my home, also in the entrypoint.sh that;s there. I already build and run the container. So i think i have to change it there? or build/run again? 

- is the --listen necessary? because off it running in docker? because i dont acces webui from other pc in my lan. 

 

Variables for AUTOMATIC1111 Container

    ENV EXTRA_OPTIONS="--upcast-sampling --listen --enable-insecure-extension  --global-extensions-access"
    ENV RENDER_GID=110
    ENV UNAME="newuser"
    ENV PUID=1000
    ENV PGID=1000

**Comment by AirGibson** [comment]
"listen" simply allows other local network systems to access the application.  Without it, you access it at your localhost of 0.0.0.0, and no other machine can access it.  If you have no need for other local machines to access it on your local IP address, you can ignore it.  I have no idea why it would have anything to do with extentions.

**Comment by AirGibson** [comment]
Also, when it comes to Environment variables (such as the EXTRA_OPTIONS that you want to alter) , you can either edit the Dockerfile before building the container, or you can override them at runtime in your docker command.  Tons of resources out there explaining all of that.
